### PR TITLE
implements help for commands

### PR DESCRIPTION
**Pull request by gblmarquez**
Actions implemented:

- [x] list  List local packages.
- [x] install  Install one or more packages.
- [x] theme  List / Use themes.
- [x] remove  Remove a theme or package.
- [x] update  Update Oh My Fish.
- [x] cd  Change directory to plugin/theme directory.
- [x] new  Create a new package from a template.
- [x] submit  Submit a package to the registry.
- [x] query  Query environment variables.
- [x] destroy  Uninstall Oh My Fish.
- [x] describe  Get information about what packages do.

### CODE REVIEW

**Comment by derekstavis** [comment]
Reviewing!

**Comment by derekstavis** [comment]
Tested here, works like a charm. LGTM :ok_hand:

**Comment by bpinto** [comment]
Thanks @gblmarquez

**Comment by bucaran** [comment]
@gblmarquez Awesome! :+1:

**Pull request merged**
