### PR TITLE
Extracting template to a file and improving it

### PR DESCRIPTION
**Pull request by bpinto**
It's hard to read the template as it was being created using `echo`
instead of being defined on a separate file. Also adding some comments
to improve the configuration file readability.

Depends on https://github.com/fish-shell/oh-my-fish/pull/528

### CODE REVIEW

**Comment by bobthecow** [comment]
:-1: this breaks xdg support

**Comment by bpinto** [comment]
How does it?

**Comment by bobthecow** [comment]
It's dynamically writing those paths to the config file, based on XDG env variables. Your version hard codes them :)

**Comment by bpinto** [comment]
I see... well, now I have to go through my usual `sed` limitations... how do to the `sed` on the file. :D

**Comment by bpinto** [comment]
`sed` works differently on OS X and linux... that's why I always have difficulties :(

**Comment by bpinto** [comment]
Redone.
ping @bobthecow

**Comment by bobthecow** [comment]
:+1: lgtm

we need to merge my config change so this will work :)

**Comment by bucaran** [comment]
:-1:

**Comment by bobthecow** [comment]
I think you misunderstand the purpose of this pull request.

**Comment by bpinto** [comment]
I agree :)

**Comment by bpinto** [comment]
@bucaran 
Why did you close? What is the problem? Let's discuss, not close the PR.

**Comment by bucaran** [comment]
@bpinto This got closed when I merged @bobthecow PR by pulling directly from his copy and adding my changes on top. A lot of stuff happened last night.

So, what are we trying to accomplish with this?

**Comment by bpinto** [comment]
Just removing hard to read `echo` calls from the init file and moving them to a template file.

**Comment by bucaran** [comment]
Cool. This is not about editing the config file, just having config templates. 

LGTM.

**Pull request merged**
