### PR TITLE
autocomplete help

### PR DESCRIPTION
**Pull request by sheldon**
making help more... helpful :sos:

### CODE REVIEW

**Comment by bpinto** [comment]
@sheldon closed? :P

**Comment by sheldon** [comment]
misclicked the delete branch cleaning up others, whoops!

**Comment by bpinto** [comment]
LGTM!

Unrelated to your issue, but with autocomplete I'm feeling my shell slow when typing some omf commands. Has anyone else noticed this?

**Comment by sheldon** [comment]
mine seems ok, nice and snappy

**Comment by bobthecow** [comment]
:+1:

**Comment by bobthecow** [comment]
@bpinto open an issue re: autocomplete slowness so we can see if others are experiencing it?

**Comment by bpinto** [comment]
@bobthecow done: https://github.com/fish-shell/oh-my-fish/issues/568

**Pull request merged**
