### PR TITLE
Adding maven plugin

### PR DESCRIPTION
**Pull request by benc**
This will colorize maven output

### CODE REVIEW

**Comment by bpinto** [comment]
@bucaran 
What do you say?

@benc 
Could you rebase with latest upstream/master?

**Comment by derekstavis** [comment]
Awesome!! Thanks!! It worked well for me!! Will surely make mvn usage less boring.

About the code, there're just two tiny details that could be fixed:

+ When command `mvn` does not exist we get this message:
```
fish: Unknown command 'mvn'
/Users/derek/.config/omf/pkg/mvn/mvn.fish (line 23):   command mvn $argv | \
                                                               ^
in function 'mvn',
	called on standard input,
	with parameter list 'help'
```

+ You can strip `- x` out from `set` inside a function:
```
function anything
  set -x WITH_X "it works"
  set WITHOUT_X "works too"

  echo $WITH_X
  echo $WITHOUT_X
else
```

**Comment by bucaran** [comment]
@benc Nice.

Please add a description to the function. `function name -d "description"` and if there is any configuration you need to load or anything you would like to do during startup add and init event handler (if there is not, you can ignore this).

**Comment by derekstavis** [comment]
Aside from recommended stuff, that's bound to the OP repository, this PR LGTM to merge @bpinto as it works as intended.

**Comment by bpinto** [comment]
Thanks @derekstavis

Waiting for @benc to fix comments above.

**Comment by benc** [comment]
@derekstavis "make mvn usage less boring", that is a very accurate description! 

I've applied the fixes, and rebased with latest upstream/master

**Comment by bucaran** [comment]
:+1: Thanks.

**Comment by derekstavis** [comment]
Thanks @benc!!!

**Pull request merged**
