### PR TITLE
Reference #517 Add default theme to database

### PR DESCRIPTION
**Pull request by bpinto**

### CODE REVIEW

**Comment by bpinto** [comment]
@bucaran I think we can fetch this theme while installing OMF, but no need to stop people from deleting it, I guess.

**Comment by bucaran** [comment]
@bpinto Or we could revert to the original behavior when there was a default theme. I would say let's prevent people from deleting it. And yes, we can fetch it during the first OMF init.

**Comment by bpinto** [comment]
@bucaran it would also work, your call.

**Comment by bucaran** [comment]
:+1: Alright.

**Pull request merged**
